version: '3'
services:
  task-service:
    build:
      context: ./task-service
    ports:
      - "8080:8080"
    networks:
      - task-net
  optimization-service:
    build:
      context: ./optimization-service
    ports:
      - "8081:8081"
    networks:
      - task-net

networks:
  task-net:
    driver: bridge
