apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimization-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: optimization-service
  template:
    metadata:
      labels:
        app: optimization-service
    spec:
      containers:
        - name: optimization-service
          image: optimization-service:latest
          ports:
            - containerPort: 8081
